name: Terraform Workflow-config-acm-fix

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform action"
        required: true
        default: ""
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: practice-422202
          install_components: gke-gcloud-auth-plugin

      # 🔥 REQUIRED: connect Terraform to existing cluster
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials gke-ha-cluster \
            --region us-central1 \
            --project practice-422202

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: config-synch

      - name: Terraform Plan
        run: terraform plan
        working-directory: config-synch

      - name: Terraform Action
        run: |
          if [ "${{ github.event.inputs.action }}" = "apply" ]; then
            terraform apply -auto-approve
          elif [ "${{ github.event.inputs.action }}" = "destroy" ]; then
            terraform destroy -auto-approve
          fi
        working-directory: config-synch
